//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacancyManager {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VacancyManager.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;br&gt;
        ///&lt;i&gt;{Message}&lt;/i&gt;&lt;br&gt;
        ///&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;Отправлено: &lt;b&gt;{Sender}, {Date}&lt;/b&gt;&lt;br&gt;
        ///.
        /// </summary>
        internal static string LastMessage {
            get {
                return ResourceManager.GetString("LastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;{Applicant}&lt;/b&gt;, для вас получено сообщение.
        ///&lt;br&gt;&lt;br&gt;
        ///Сообщение #{Id} по вакансии: &quot;{Vacancy}&quot;
        ///&lt;br&gt;&lt;br&gt;
        ///&lt;i&gt;{Message}&lt;/i&gt;&lt;br&gt;
        ///&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;&amp;nbsp;Отправлено: &lt;b&gt;{Sender}, {Date}&lt;/b&gt;
        ///&lt;br&gt;
        ///&lt;br&gt;
        ///Прошлые сообщения для вас:
        ///.
        /// </summary>
        internal static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #{Id}.
        /// </summary>
        internal static string NewMessage_Topic {
            get {
                return ResourceManager.GetString("NewMessage_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать, {UserName}.
        ///Твой мыло {Email}..
        /// </summary>
        internal static string UserAdd {
            get {
                return ResourceManager.GetString("UserAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добро пожаловать.
        /// </summary>
        internal static string UserAdd_Topic {
            get {
                return ResourceManager.GetString("UserAdd_Topic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {UserName}, тебя удалили!.
        /// </summary>
        internal static string UserDelete {
            get {
                return ResourceManager.GetString("UserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вас удалили.
        /// </summary>
        internal static string UserDelete_Topic {
            get {
                return ResourceManager.GetString("UserDelete_Topic", resourceCulture);
            }
        }
    }
}
