//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.431
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacancyManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VacancyManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить соискателя.
        /// </summary>
        public static string AddApplicant {
            get {
                return ResourceManager.GetString("AddApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дополнительное образование.
        /// </summary>
        public static string AdditionalInformation {
            get {
                return ResourceManager.GetString("AdditionalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить требование.
        /// </summary>
        public static string AddRequirementToStack {
            get {
                return ResourceManager.GetString("AddRequirementToStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Административная панель менеджера вакансий.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактор соискателя.
        /// </summary>
        public static string ApplicantEdit {
            get {
                return ResourceManager.GetString("ApplicantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список соискателей.
        /// </summary>
        public static string ApplicantList {
            get {
                return ResourceManager.GetString("ApplicantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый соискатель.
        /// </summary>
        public static string ApplicantNew {
            get {
                return ResourceManager.GetString("ApplicantNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Соискатели.
        /// </summary>
        public static string Applicants {
            get {
                return ResourceManager.GetString("Applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вложения.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить соискателя.
        /// </summary>
        public static string btnAddConsideration {
            get {
                return ResourceManager.GetString("btnAddConsideration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новая категория.
        /// </summary>
        public static string btnAddRequirementStack {
            get {
                return ResourceManager.GetString("btnAddRequirementStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарии.
        /// </summary>
        public static string btnCommentsView {
            get {
                return ResourceManager.GetString("btnCommentsView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить соискателя.
        /// </summary>
        public static string btnDeleteConsideration {
            get {
                return ResourceManager.GetString("btnDeleteConsideration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скрыть.
        /// </summary>
        public static string btnHide {
            get {
                return ResourceManager.GetString("btnHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить стек требований.
        /// </summary>
        public static string btnRemoveRequirementStak {
            get {
                return ResourceManager.GetString("btnRemoveRequirementStak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показать.
        /// </summary>
        public static string btnShow {
            get {
                return ResourceManager.GetString("btnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сертификаты и тренинги.
        /// </summary>
        public static string CertsTraining {
            get {
                return ResourceManager.GetString("CertsTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компетенция.
        /// </summary>
        public static string Competency {
            get {
                return ResourceManager.GetString("Competency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурация.
        /// </summary>
        public static string Conf {
            get {
                return ResourceManager.GetString("Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение параметра.
        /// </summary>
        public static string ConfEdit {
            get {
                return ResourceManager.GetString("ConfEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Конфигурация.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметр.
        /// </summary>
        public static string ConfName {
            get {
                return ResourceManager.GetString("ConfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый параметр.
        /// </summary>
        public static string ConfNew {
            get {
                return ResourceManager.GetString("ConfNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Контактный телефон.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление категории.
        /// </summary>
        public static string CreateRequirementStackList {
            get {
                return ResourceManager.GetString("CreateRequirementStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Получено.
        /// </summary>
        public static string DeliveryDate {
            get {
                return ResourceManager.GetString("DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исполняемые обязанности.
        /// </summary>
        public static string Duties {
            get {
                return ResourceManager.GetString("Duties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение категории.
        /// </summary>
        public static string EditRequirementStackList {
            get {
                return ResourceManager.GetString("EditRequirementStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Образование.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Используемые технологии.
        /// </summary>
        public static string ExperienceRequirements {
            get {
                return ResourceManager.GetString("ExperienceRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ФИО.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Входящие сообщения.
        /// </summary>
        public static string InputMessages {
            get {
                return ResourceManager.GetString("InputMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сообщения.
        /// </summary>
        public static string MailMessages {
            get {
                return ResourceManager.GetString("MailMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр сообщений....
        /// </summary>
        public static string MessageFilter {
            get {
                return ResourceManager.GetString("MessageFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст сообщения.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбрана категория.
        /// </summary>
        public static string msgRequirementStackNotSelected {
            get {
                return ResourceManager.GetString("msgRequirementStackNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Position_en {
            get {
                return ResourceManager.GetString("Position_en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        public static string Position_ru {
            get {
                return ResourceManager.GetString("Position_ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Профессиональный опыт.
        /// </summary>
        public static string ProfExp {
            get {
                return ResourceManager.GetString("ProfExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проект.
        /// </summary>
        public static string ProfExpProject {
            get {
                return ResourceManager.GetString("ProfExpProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt;Август 2007&lt;br&gt;&lt;br&gt;Example: August 2007 .
        /// </summary>
        public static string QT_BeginExp {
            get {
                return ResourceManager.GetString("QT_BeginExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt;Кафедра системного программирования..
        /// </summary>
        public static string QT_Cafedra {
            get {
                return ResourceManager.GetString("QT_Cafedra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt; Математико-механический факультет.&lt;br&gt;&lt;br&gt;Example: &lt;br&gt;Department of software engineering..
        /// </summary>
        public static string QT_Department {
            get {
                return ResourceManager.GetString("QT_Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt;- распределение обязанностей в команде из 10 человек&lt;br&gt;- проектирование архитектуры создаваемых приложений&lt;br&gt;- написание бизнес-логики приложений&lt;br&gt;- рефакторинг существующего кода&lt;br&gt;- написание запросов к БД и хранимых процедур (pl/pgSQL)&lt;br&gt;- работа с БД: Hibernate(SQL, HQL), JDBC.&lt;br&gt;&lt;br&gt;Example:&lt;br&gt;Project coordination (1 team of 10 persons).&lt;br&gt;Direct customer interactions. &lt;br&gt;Development process organization, tracking and maintenance. &lt;br&gt;Project planning. Modules design and Developme [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QT_Duties {
            get {
                return ResourceManager.GetString("QT_Duties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt; Санкт -Петербургский&lt;br&gt;Государственный &lt;br&gt;Университет&lt;br&gt;&lt;br&gt;Example: &lt;br&gt;Saint-Petersburg State University..
        /// </summary>
        public static string QT_EduPlace {
            get {
                return ResourceManager.GetString("QT_EduPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt;Май 2008&lt;br&gt;&lt;br&gt;Example: May 2008.
        /// </summary>
        public static string QT_EndExp {
            get {
                return ResourceManager.GetString("QT_EndExp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt;Ланит-Терком&lt;br&gt;&lt;br&gt;Example: &lt;br&gt;Lanit-Tercom.
        /// </summary>
        public static string QT_Job {
            get {
                return ResourceManager.GetString("QT_Job", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt;Август 2007 – Май 2008&lt;br&gt;&lt;br&gt;Example August 2007 – May 2008.
        /// </summary>
        public static string QT_Period {
            get {
                return ResourceManager.GetString("QT_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример &lt;br&gt; Руководитель группы разработчиков&lt;br&gt;&lt;br&gt; Example &lt;br&gt; Team lead.
        /// </summary>
        public static string QT_Position {
            get {
                return ResourceManager.GetString("QT_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt;Проект1- Информационная система обеспечения &lt;br&gt;социальной поддержки населения области&lt;br&gt;
        ///Назначение: автоматизация процессов предоставления &lt;br&gt;социальной помощи населению&lt;br&gt;&lt;br&gt;
        ///Example:&lt;br&gt;Project1- Passenger Information System for trains..
        /// </summary>
        public static string QT_Project {
            get {
                return ResourceManager.GetString("QT_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt;Аспирантура.&lt;br&gt;&lt;br&gt;Example: &lt;br&gt;As post-graduate student..
        /// </summary>
        public static string QT_Status {
            get {
                return ResourceManager.GetString("QT_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример&lt;br&gt;1 год опыта работы руководителем группы разработчиков.&lt;br&gt;5 лет опыта работы разработчиком ПО. &lt;br&gt;Опыт использования гибких методологий разработки (Scrum, XP) &lt;br&gt;Опыт управления неоднородными командами из 10 человек&lt;br&gt;Опыт управления удаленными командами&lt;br&gt;Опыт тесного контакта с заказчиком, включая участие в выработке и анализе требований, &lt;br&gt;анализе рисков, управлении продуктов и работу с партнерами заказчика от его имени&lt;br&gt;Системное администрирование Windows и Linux&lt;br&gt;Математическое обра [rest of string was truncated]&quot;;.
        /// </summary>
        public static string QT_Summary {
            get {
                return ResourceManager.GetString("QT_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пример: &lt;br&gt;Прошел тренинги компании ScrumTrek:&lt;br&gt; «Agile Development with Scrum», «Test Driven Developement»&lt;br&gt; &lt;br&gt; Example: &lt;br&gt; If there are no options, erase the item..
        /// </summary>
        public static string QT_Training {
            get {
                return ResourceManager.GetString("QT_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реквизит резюме является обязателеным для заполнения.
        /// </summary>
        public static string RequiredMessage {
            get {
                return ResourceManager.GetString("RequiredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список требований.
        /// </summary>
        public static string RequirementListinStack {
            get {
                return ResourceManager.GetString("RequirementListinStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требования.
        /// </summary>
        public static string RequirementsTabTitle {
            get {
                return ResourceManager.GetString("RequirementsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список категорий.
        /// </summary>
        public static string RequirementStackList {
            get {
                return ResourceManager.GetString("RequirementStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Резюме.
        /// </summary>
        public static string Resumes {
            get {
                return ResourceManager.GetString("Resumes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправлено.
        /// </summary>
        public static string SendDate {
            get {
                return ResourceManager.GetString("SendDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправитель.
        /// </summary>
        public static string Sender {
            get {
                return ResourceManager.GetString("Sender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отправить сообщение.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навык.
        /// </summary>
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Навыки.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тема.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткая информация.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Языки программирования, технологии ,стандарты, среды,  библиотеки.
        /// </summary>
        public static string Technologies {
            get {
                return ResourceManager.GetString("Technologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to df.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требование.
        /// </summary>
        public static string TitleRequirementName {
            get {
                return ResourceManager.GetString("TitleRequirementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требование (На английском языке).
        /// </summary>
        public static string TitleRequirementNameEn {
            get {
                return ResourceManager.GetString("TitleRequirementNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string TitleRequirementStackName {
            get {
                return ResourceManager.GetString("TitleRequirementStackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория (На английском языке).
        /// </summary>
        public static string TitleRequirementStackNameEn {
            get {
                return ResourceManager.GetString("TitleRequirementStackNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление требования.
        /// </summary>
        public static string TitleWindowCreateRequirement {
            get {
                return ResourceManager.GetString("TitleWindowCreateRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование требования.
        /// </summary>
        public static string TitleWindowEditRequirement {
            get {
                return ResourceManager.GetString("TitleWindowEditRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить пользователя.
        /// </summary>
        public static string UserBDelete {
            get {
                return ResourceManager.GetString("UserBDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактировать пользователя.
        /// </summary>
        public static string UserBEdit {
            get {
                return ResourceManager.GetString("UserBEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забанить/Разбанить.
        /// </summary>
        public static string UserBLockUnlock {
            get {
                return ResourceManager.GetString("UserBLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пользователь.
        /// </summary>
        public static string UserBNewUser {
            get {
                return ResourceManager.GetString("UserBNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string UserCommentary {
            get {
                return ResourceManager.GetString("UserCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string UserCreationDate {
            get {
                return ResourceManager.GetString("UserCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забанен.
        /// </summary>
        public static string UserIsLockedOut {
            get {
                return ResourceManager.GetString("UserIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата.
        /// </summary>
        public static string UserLastLockedOutDate {
            get {
                return ResourceManager.GetString("UserLastLockedOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина.
        /// </summary>
        public static string UserLastLockedOutReason {
            get {
                return ResourceManager.GetString("UserLastLockedOutReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний визит.
        /// </summary>
        public static string UserLastLoginDate {
            get {
                return ResourceManager.GetString("UserLastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активирован.
        /// </summary>
        public static string UserList_IsActivated {
            get {
                return ResourceManager.GetString("UserList_IsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показано  {0} - {1} из {2}.
        /// </summary>
        public static string UserToolbarDislpayMsg {
            get {
                return ResourceManager.GetString("UserToolbarDislpayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных для отображения.
        /// </summary>
        public static string UserToolbarEmptyMsg {
            get {
                return ResourceManager.GetString("UserToolbarEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансии.
        /// </summary>
        public static string Vacancies {
            get {
                return ResourceManager.GetString("Vacancies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вакансия.
        /// </summary>
        public static string Vacancy {
            get {
                return ResourceManager.GetString("Vacancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
