//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.269
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacancyManager.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VacancyManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить требование к стеку.
        /// </summary>
        public static string AddRequirementToStack {
            get {
                return ResourceManager.GetString("AddRequirementToStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Административная панель менеджера вакансий.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор соискателя.
        /// </summary>
        public static string ApplicantEdit {
            get {
                return ResourceManager.GetString("ApplicantEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список соискателей.
        /// </summary>
        public static string ApplicantList {
            get {
                return ResourceManager.GetString("ApplicantList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый соискатель.
        /// </summary>
        public static string ApplicantNew {
            get {
                return ResourceManager.GetString("ApplicantNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый стек требований.
        /// </summary>
        public static string btnAddRequirementStack {
            get {
                return ResourceManager.GetString("btnAddRequirementStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть.
        /// </summary>
        public static string btnHide {
            get {
                return ResourceManager.GetString("btnHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        public static string btnRemove {
            get {
                return ResourceManager.GetString("btnRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить стек требований.
        /// </summary>
        public static string btnRemoveRequirementStak {
            get {
                return ResourceManager.GetString("btnRemoveRequirementStak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать.
        /// </summary>
        public static string btnShow {
            get {
                return ResourceManager.GetString("btnShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Конфигурация.
        /// </summary>
        public static string Conf {
            get {
                return ResourceManager.GetString("Conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение параметра.
        /// </summary>
        public static string ConfEdit {
            get {
                return ResourceManager.GetString("ConfEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметр.
        /// </summary>
        public static string ConfName {
            get {
                return ResourceManager.GetString("ConfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый параметр.
        /// </summary>
        public static string ConfNew {
            get {
                return ResourceManager.GetString("ConfNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Контактный телефон.
        /// </summary>
        public static string ContactPhone {
            get {
                return ResourceManager.GetString("ContactPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление стека требований.
        /// </summary>
        public static string CreateRequirementStackList {
            get {
                return ResourceManager.GetString("CreateRequirementStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Изменение стека требований.
        /// </summary>
        public static string EditRequirementStackList {
            get {
                return ResourceManager.GetString("EditRequirementStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ФИО.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран стек требований.
        /// </summary>
        public static string msgRequirementStackNotSelected {
            get {
                return ResourceManager.GetString("msgRequirementStackNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список требований в стеке.
        /// </summary>
        public static string RequirementListinStack {
            get {
                return ResourceManager.GetString("RequirementListinStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требования.
        /// </summary>
        public static string RequirementsTabTitle {
            get {
                return ResourceManager.GetString("RequirementsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список стеков требований.
        /// </summary>
        public static string RequirementStackList {
            get {
                return ResourceManager.GetString("RequirementStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навык.
        /// </summary>
        public static string Skill {
            get {
                return ResourceManager.GetString("Skill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Навыки.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Требование.
        /// </summary>
        public static string TitleRequirementName {
            get {
                return ResourceManager.GetString("TitleRequirementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Стек требований.
        /// </summary>
        public static string TitleRequirementStackName {
            get {
                return ResourceManager.GetString("TitleRequirementStackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление требования.
        /// </summary>
        public static string TitleWindowCreateRequirement {
            get {
                return ResourceManager.GetString("TitleWindowCreateRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование требования.
        /// </summary>
        public static string TitleWindowEditRequirement {
            get {
                return ResourceManager.GetString("TitleWindowEditRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить пользователя.
        /// </summary>
        public static string UserBDelete {
            get {
                return ResourceManager.GetString("UserBDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать пользователя.
        /// </summary>
        public static string UserBEdit {
            get {
                return ResourceManager.GetString("UserBEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забанить/Разбанить.
        /// </summary>
        public static string UserBLockUnlock {
            get {
                return ResourceManager.GetString("UserBLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый пользователь.
        /// </summary>
        public static string UserBNewUser {
            get {
                return ResourceManager.GetString("UserBNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Комментарий.
        /// </summary>
        public static string UserCommentary {
            get {
                return ResourceManager.GetString("UserCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата создания.
        /// </summary>
        public static string UserCreationDate {
            get {
                return ResourceManager.GetString("UserCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-Mail.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Забанен.
        /// </summary>
        public static string UserIsLockedOut {
            get {
                return ResourceManager.GetString("UserIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата последне блокировки.
        /// </summary>
        public static string UserLastLockedOutDate {
            get {
                return ResourceManager.GetString("UserLastLockedOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Причина последней блокировки.
        /// </summary>
        public static string UserLastLockedOutReason {
            get {
                return ResourceManager.GetString("UserLastLockedOutReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Последний визит.
        /// </summary>
        public static string UserLastLoginDate {
            get {
                return ResourceManager.GetString("UserLastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Активирован.
        /// </summary>
        public static string UserList_IsActivated {
            get {
                return ResourceManager.GetString("UserList_IsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Роли.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показано  {0} - {1} из {2}.
        /// </summary>
        public static string UserToolbarDislpayMsg {
            get {
                return ResourceManager.GetString("UserToolbarDislpayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нет данных для отображения.
        /// </summary>
        public static string UserToolbarEmptyMsg {
            get {
                return ResourceManager.GetString("UserToolbarEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
