//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VacancyManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VacancyManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить требование к стеку.
        /// </summary>
        public static string AddRequirementToStack {
            get {
                return ResourceManager.GetString("AddRequirementToStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Административная панель менеджера вакансий.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый стек требований.
        /// </summary>
        public static string btnAddRequirementStack {
            get {
                return ResourceManager.GetString("btnAddRequirementStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить стек требований.
        /// </summary>
        public static string btnRemoveRequirementStak {
            get {
                return ResourceManager.GetString("btnRemoveRequirementStak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string btnSave {
            get {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление стека требований.
        /// </summary>
        public static string CreateRequirementStackList {
            get {
                return ResourceManager.GetString("CreateRequirementStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение стека требований.
        /// </summary>
        public static string EditRequirementStackList {
            get {
                return ResourceManager.GetString("EditRequirementStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран стек требований.
        /// </summary>
        public static string msgRequirementStackNotSelected {
            get {
                return ResourceManager.GetString("msgRequirementStackNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список требований в стеке.
        /// </summary>
        public static string RequirementListinStack {
            get {
                return ResourceManager.GetString("RequirementListinStack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требования.
        /// </summary>
        public static string RequirementsTabTitle {
            get {
                return ResourceManager.GetString("RequirementsTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список стеков требований.
        /// </summary>
        public static string RequirementStackList {
            get {
                return ResourceManager.GetString("RequirementStackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Требование.
        /// </summary>
        public static string TitleRequirementName {
            get {
                return ResourceManager.GetString("TitleRequirementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стек требований.
        /// </summary>
        public static string TitleRequirementStackName {
            get {
                return ResourceManager.GetString("TitleRequirementStackName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавление требования.
        /// </summary>
        public static string TitleWindowCreateRequirement {
            get {
                return ResourceManager.GetString("TitleWindowCreateRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редактирование требования.
        /// </summary>
        public static string TitleWindowEditRequirement {
            get {
                return ResourceManager.GetString("TitleWindowEditRequirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить пользователя.
        /// </summary>
        public static string UserBDelete {
            get {
                return ResourceManager.GetString("UserBDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забанить/Разбанить.
        /// </summary>
        public static string UserBLockUnlock {
            get {
                return ResourceManager.GetString("UserBLockUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пользователь.
        /// </summary>
        public static string UserBNewUser {
            get {
                return ResourceManager.GetString("UserBNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначит роли.
        /// </summary>
        public static string UserBSetRoles {
            get {
                return ResourceManager.GetString("UserBSetRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Комментарий.
        /// </summary>
        public static string UserCommentary {
            get {
                return ResourceManager.GetString("UserCommentary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата создания.
        /// </summary>
        public static string UserCreationDate {
            get {
                return ResourceManager.GetString("UserCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string UserEmail {
            get {
                return ResourceManager.GetString("UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Забанен.
        /// </summary>
        public static string UserIsLockedOut {
            get {
                return ResourceManager.GetString("UserIsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата последне блокировки.
        /// </summary>
        public static string UserLastLockedOutDate {
            get {
                return ResourceManager.GetString("UserLastLockedOutDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Причина последней блокировки.
        /// </summary>
        public static string UserLastLockedOutReason {
            get {
                return ResourceManager.GetString("UserLastLockedOutReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последний визит.
        /// </summary>
        public static string UserLastLoginDate {
            get {
                return ResourceManager.GetString("UserLastLoginDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активирован.
        /// </summary>
        public static string UserList_IsActivated {
            get {
                return ResourceManager.GetString("UserList_IsActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Роли.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Показано  {0} - {1} из {2}.
        /// </summary>
        public static string UserToolbarDislpayMsg {
            get {
                return ResourceManager.GetString("UserToolbarDislpayMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет данных для отображения.
        /// </summary>
        public static string UserToolbarEmptyMsg {
            get {
                return ResourceManager.GetString("UserToolbarEmptyMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предупреждение.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
